<Project Sdk="Godot.NET.Sdk/4.5.0-beta.3">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="materials\shader_materials\compute_heightmap.glsl"/>
        <Content Include="materials\shader_materials\compute_heightmap_sampler.glsl"/>
        <Content Include="materials\shader_materials\get_vertex_heights.glsl"/>
    </ItemGroup>
</Project>