// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerMovementProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Planets {

  /// <summary>Holder for reflection information generated from PlayerMovementProto.proto</summary>
  public static partial class PlayerMovementProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerMovementProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerMovementProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlQbGF5ZXJNb3ZlbWVudFByb3RvLnByb3RvEgdQbGFuZXRzGhJQcm90b1Zl",
            "Y3RvcjMucHJvdG8ilgIKE1BsYXllck1vdmVtZW50UHJvdG8SNAoVQ3VycmVu",
            "dEdsb2JhbFBvc2l0aW9uGAEgASgLMhUuUGxhbmV0cy5Qcm90b1ZlY3RvcjMS",
            "JwoIVmVsb2NpdHkYAiABKAsyFS5QbGFuZXRzLlByb3RvVmVjdG9yMxInCghS",
            "b3RhdGlvbhgDIAEoCzIVLlBsYW5ldHMuUHJvdG9WZWN0b3IzEiEKAlVwGAQg",
            "ASgLMhUuUGxhbmV0cy5Qcm90b1ZlY3RvcjMSMAoRTW92ZW1lbnREaXJlY3Rp",
            "b24YBSABKAsyFS5QbGFuZXRzLlByb3RvVmVjdG9yMxIRCglJc0p1bXBpbmcY",
            "BiABKAgSDwoHSXNJbkFpchgHIAEoCEIKqgIHUGxhbmV0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Planets.ProtoVector3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Planets.PlayerMovementProto), global::Planets.PlayerMovementProto.Parser, new[]{ "CurrentGlobalPosition", "Velocity", "Rotation", "Up", "MovementDirection", "IsJumping", "IsInAir" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerMovementProto : pb::IMessage<PlayerMovementProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerMovementProto> _parser = new pb::MessageParser<PlayerMovementProto>(() => new PlayerMovementProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerMovementProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Planets.PlayerMovementProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMovementProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMovementProto(PlayerMovementProto other) : this() {
      currentGlobalPosition_ = other.currentGlobalPosition_ != null ? other.currentGlobalPosition_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      up_ = other.up_ != null ? other.up_.Clone() : null;
      movementDirection_ = other.movementDirection_ != null ? other.movementDirection_.Clone() : null;
      isJumping_ = other.isJumping_;
      isInAir_ = other.isInAir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMovementProto Clone() {
      return new PlayerMovementProto(this);
    }

    /// <summary>Field number for the "CurrentGlobalPosition" field.</summary>
    public const int CurrentGlobalPositionFieldNumber = 1;
    private global::Planets.ProtoVector3 currentGlobalPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 CurrentGlobalPosition {
      get { return currentGlobalPosition_; }
      set {
        currentGlobalPosition_ = value;
      }
    }

    /// <summary>Field number for the "Velocity" field.</summary>
    public const int VelocityFieldNumber = 2;
    private global::Planets.ProtoVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "Rotation" field.</summary>
    public const int RotationFieldNumber = 3;
    private global::Planets.ProtoVector3 rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "Up" field.</summary>
    public const int UpFieldNumber = 4;
    private global::Planets.ProtoVector3 up_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 Up {
      get { return up_; }
      set {
        up_ = value;
      }
    }

    /// <summary>Field number for the "MovementDirection" field.</summary>
    public const int MovementDirectionFieldNumber = 5;
    private global::Planets.ProtoVector3 movementDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 MovementDirection {
      get { return movementDirection_; }
      set {
        movementDirection_ = value;
      }
    }

    /// <summary>Field number for the "IsJumping" field.</summary>
    public const int IsJumpingFieldNumber = 6;
    private bool isJumping_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsJumping {
      get { return isJumping_; }
      set {
        isJumping_ = value;
      }
    }

    /// <summary>Field number for the "IsInAir" field.</summary>
    public const int IsInAirFieldNumber = 7;
    private bool isInAir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsInAir {
      get { return isInAir_; }
      set {
        isInAir_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerMovementProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerMovementProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrentGlobalPosition, other.CurrentGlobalPosition)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!object.Equals(Up, other.Up)) return false;
      if (!object.Equals(MovementDirection, other.MovementDirection)) return false;
      if (IsJumping != other.IsJumping) return false;
      if (IsInAir != other.IsInAir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currentGlobalPosition_ != null) hash ^= CurrentGlobalPosition.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (up_ != null) hash ^= Up.GetHashCode();
      if (movementDirection_ != null) hash ^= MovementDirection.GetHashCode();
      if (IsJumping != false) hash ^= IsJumping.GetHashCode();
      if (IsInAir != false) hash ^= IsInAir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currentGlobalPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentGlobalPosition);
      }
      if (velocity_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Velocity);
      }
      if (rotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rotation);
      }
      if (up_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Up);
      }
      if (movementDirection_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MovementDirection);
      }
      if (IsJumping != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsJumping);
      }
      if (IsInAir != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsInAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currentGlobalPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentGlobalPosition);
      }
      if (velocity_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Velocity);
      }
      if (rotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rotation);
      }
      if (up_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Up);
      }
      if (movementDirection_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MovementDirection);
      }
      if (IsJumping != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsJumping);
      }
      if (IsInAir != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsInAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currentGlobalPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentGlobalPosition);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (up_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Up);
      }
      if (movementDirection_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MovementDirection);
      }
      if (IsJumping != false) {
        size += 1 + 1;
      }
      if (IsInAir != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerMovementProto other) {
      if (other == null) {
        return;
      }
      if (other.currentGlobalPosition_ != null) {
        if (currentGlobalPosition_ == null) {
          CurrentGlobalPosition = new global::Planets.ProtoVector3();
        }
        CurrentGlobalPosition.MergeFrom(other.CurrentGlobalPosition);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Planets.ProtoVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::Planets.ProtoVector3();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.up_ != null) {
        if (up_ == null) {
          Up = new global::Planets.ProtoVector3();
        }
        Up.MergeFrom(other.Up);
      }
      if (other.movementDirection_ != null) {
        if (movementDirection_ == null) {
          MovementDirection = new global::Planets.ProtoVector3();
        }
        MovementDirection.MergeFrom(other.MovementDirection);
      }
      if (other.IsJumping != false) {
        IsJumping = other.IsJumping;
      }
      if (other.IsInAir != false) {
        IsInAir = other.IsInAir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currentGlobalPosition_ == null) {
              CurrentGlobalPosition = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(CurrentGlobalPosition);
            break;
          }
          case 18: {
            if (velocity_ == null) {
              Velocity = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 26: {
            if (rotation_ == null) {
              Rotation = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 34: {
            if (up_ == null) {
              Up = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Up);
            break;
          }
          case 42: {
            if (movementDirection_ == null) {
              MovementDirection = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(MovementDirection);
            break;
          }
          case 48: {
            IsJumping = input.ReadBool();
            break;
          }
          case 56: {
            IsInAir = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currentGlobalPosition_ == null) {
              CurrentGlobalPosition = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(CurrentGlobalPosition);
            break;
          }
          case 18: {
            if (velocity_ == null) {
              Velocity = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 26: {
            if (rotation_ == null) {
              Rotation = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 34: {
            if (up_ == null) {
              Up = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Up);
            break;
          }
          case 42: {
            if (movementDirection_ == null) {
              MovementDirection = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(MovementDirection);
            break;
          }
          case 48: {
            IsJumping = input.ReadBool();
            break;
          }
          case 56: {
            IsInAir = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
