// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerDataProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Planets {

  /// <summary>Holder for reflection information generated from PlayerDataProto.proto</summary>
  public static partial class PlayerDataProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerDataProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerDataProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQbGF5ZXJEYXRhUHJvdG8ucHJvdG8SB1BsYW5ldHMaElByb3RvVmVjdG9y",
            "My5wcm90byKBAgoPUGxheWVyRGF0YVByb3RvEicKCFBvc2l0aW9uGAEgASgL",
            "MhUuUGxhbmV0cy5Qcm90b1ZlY3RvcjMSLAoNU3Bhd25Qb3NpdGlvbhgCIAEo",
            "CzIVLlBsYW5ldHMuUHJvdG9WZWN0b3IzEiEKAlVwGAMgASgLMhUuUGxhbmV0",
            "cy5Qcm90b1ZlY3RvcjMSDQoFU3BlZWQYBCABKAUSEQoJSnVtcFNwZWVkGAUg",
            "ASgFEhgKEE1vdXNlU2Vuc2l0aXZpdHkYBiABKAISEwoLU3Bhd25QbGFuZXQY",
            "ByABKAkSFQoNQ3VycmVudFBsYW5ldBgIIAEoCRIMCgRVdWlkGAkgASgJQgqq",
            "AgdQbGFuZXRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Planets.ProtoVector3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Planets.PlayerDataProto), global::Planets.PlayerDataProto.Parser, new[]{ "Position", "SpawnPosition", "Up", "Speed", "JumpSpeed", "MouseSensitivity", "SpawnPlanet", "CurrentPlanet", "Uuid" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerDataProto : pb::IMessage<PlayerDataProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerDataProto> _parser = new pb::MessageParser<PlayerDataProto>(() => new PlayerDataProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerDataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Planets.PlayerDataProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDataProto(PlayerDataProto other) : this() {
      position_ = other.position_ != null ? other.position_.Clone() : null;
      spawnPosition_ = other.spawnPosition_ != null ? other.spawnPosition_.Clone() : null;
      up_ = other.up_ != null ? other.up_.Clone() : null;
      speed_ = other.speed_;
      jumpSpeed_ = other.jumpSpeed_;
      mouseSensitivity_ = other.mouseSensitivity_;
      spawnPlanet_ = other.spawnPlanet_;
      currentPlanet_ = other.currentPlanet_;
      uuid_ = other.uuid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDataProto Clone() {
      return new PlayerDataProto(this);
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::Planets.ProtoVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "SpawnPosition" field.</summary>
    public const int SpawnPositionFieldNumber = 2;
    private global::Planets.ProtoVector3 spawnPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 SpawnPosition {
      get { return spawnPosition_; }
      set {
        spawnPosition_ = value;
      }
    }

    /// <summary>Field number for the "Up" field.</summary>
    public const int UpFieldNumber = 3;
    private global::Planets.ProtoVector3 up_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Planets.ProtoVector3 Up {
      get { return up_; }
      set {
        up_ = value;
      }
    }

    /// <summary>Field number for the "Speed" field.</summary>
    public const int SpeedFieldNumber = 4;
    private int speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "JumpSpeed" field.</summary>
    public const int JumpSpeedFieldNumber = 5;
    private int jumpSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int JumpSpeed {
      get { return jumpSpeed_; }
      set {
        jumpSpeed_ = value;
      }
    }

    /// <summary>Field number for the "MouseSensitivity" field.</summary>
    public const int MouseSensitivityFieldNumber = 6;
    private float mouseSensitivity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MouseSensitivity {
      get { return mouseSensitivity_; }
      set {
        mouseSensitivity_ = value;
      }
    }

    /// <summary>Field number for the "SpawnPlanet" field.</summary>
    public const int SpawnPlanetFieldNumber = 7;
    private string spawnPlanet_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SpawnPlanet {
      get { return spawnPlanet_; }
      set {
        spawnPlanet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CurrentPlanet" field.</summary>
    public const int CurrentPlanetFieldNumber = 8;
    private string currentPlanet_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentPlanet {
      get { return currentPlanet_; }
      set {
        currentPlanet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Uuid" field.</summary>
    public const int UuidFieldNumber = 9;
    private string uuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerDataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerDataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(SpawnPosition, other.SpawnPosition)) return false;
      if (!object.Equals(Up, other.Up)) return false;
      if (Speed != other.Speed) return false;
      if (JumpSpeed != other.JumpSpeed) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MouseSensitivity, other.MouseSensitivity)) return false;
      if (SpawnPlanet != other.SpawnPlanet) return false;
      if (CurrentPlanet != other.CurrentPlanet) return false;
      if (Uuid != other.Uuid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (position_ != null) hash ^= Position.GetHashCode();
      if (spawnPosition_ != null) hash ^= SpawnPosition.GetHashCode();
      if (up_ != null) hash ^= Up.GetHashCode();
      if (Speed != 0) hash ^= Speed.GetHashCode();
      if (JumpSpeed != 0) hash ^= JumpSpeed.GetHashCode();
      if (MouseSensitivity != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MouseSensitivity);
      if (SpawnPlanet.Length != 0) hash ^= SpawnPlanet.GetHashCode();
      if (CurrentPlanet.Length != 0) hash ^= CurrentPlanet.GetHashCode();
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (position_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      if (spawnPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpawnPosition);
      }
      if (up_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Up);
      }
      if (Speed != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Speed);
      }
      if (JumpSpeed != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(JumpSpeed);
      }
      if (MouseSensitivity != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(MouseSensitivity);
      }
      if (SpawnPlanet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SpawnPlanet);
      }
      if (CurrentPlanet.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CurrentPlanet);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (position_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      if (spawnPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpawnPosition);
      }
      if (up_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Up);
      }
      if (Speed != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Speed);
      }
      if (JumpSpeed != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(JumpSpeed);
      }
      if (MouseSensitivity != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(MouseSensitivity);
      }
      if (SpawnPlanet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SpawnPlanet);
      }
      if (CurrentPlanet.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CurrentPlanet);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (spawnPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpawnPosition);
      }
      if (up_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Up);
      }
      if (Speed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Speed);
      }
      if (JumpSpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(JumpSpeed);
      }
      if (MouseSensitivity != 0F) {
        size += 1 + 4;
      }
      if (SpawnPlanet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpawnPlanet);
      }
      if (CurrentPlanet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentPlanet);
      }
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerDataProto other) {
      if (other == null) {
        return;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Planets.ProtoVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.spawnPosition_ != null) {
        if (spawnPosition_ == null) {
          SpawnPosition = new global::Planets.ProtoVector3();
        }
        SpawnPosition.MergeFrom(other.SpawnPosition);
      }
      if (other.up_ != null) {
        if (up_ == null) {
          Up = new global::Planets.ProtoVector3();
        }
        Up.MergeFrom(other.Up);
      }
      if (other.Speed != 0) {
        Speed = other.Speed;
      }
      if (other.JumpSpeed != 0) {
        JumpSpeed = other.JumpSpeed;
      }
      if (other.MouseSensitivity != 0F) {
        MouseSensitivity = other.MouseSensitivity;
      }
      if (other.SpawnPlanet.Length != 0) {
        SpawnPlanet = other.SpawnPlanet;
      }
      if (other.CurrentPlanet.Length != 0) {
        CurrentPlanet = other.CurrentPlanet;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (position_ == null) {
              Position = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 18: {
            if (spawnPosition_ == null) {
              SpawnPosition = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(SpawnPosition);
            break;
          }
          case 26: {
            if (up_ == null) {
              Up = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Up);
            break;
          }
          case 32: {
            Speed = input.ReadInt32();
            break;
          }
          case 40: {
            JumpSpeed = input.ReadInt32();
            break;
          }
          case 53: {
            MouseSensitivity = input.ReadFloat();
            break;
          }
          case 58: {
            SpawnPlanet = input.ReadString();
            break;
          }
          case 66: {
            CurrentPlanet = input.ReadString();
            break;
          }
          case 74: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (position_ == null) {
              Position = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 18: {
            if (spawnPosition_ == null) {
              SpawnPosition = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(SpawnPosition);
            break;
          }
          case 26: {
            if (up_ == null) {
              Up = new global::Planets.ProtoVector3();
            }
            input.ReadMessage(Up);
            break;
          }
          case 32: {
            Speed = input.ReadInt32();
            break;
          }
          case 40: {
            JumpSpeed = input.ReadInt32();
            break;
          }
          case 53: {
            MouseSensitivity = input.ReadFloat();
            break;
          }
          case 58: {
            SpawnPlanet = input.ReadString();
            break;
          }
          case 66: {
            CurrentPlanet = input.ReadString();
            break;
          }
          case 74: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
